// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: grpc/grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=Op,proto3" json:"Op,omitempty"`
	M1            *Matrix                `protobuf:"bytes,2,opt,name=m1,proto3" json:"m1,omitempty"`
	M2            *Matrix                `protobuf:"bytes,3,opt,name=m2,proto3" json:"m2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Request) GetM1() *Matrix {
	if x != nil {
		return x.M1
	}
	return nil
}

func (x *Request) GetM2() *Matrix {
	if x != nil {
		return x.M2
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M             *Matrix                `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_grpc_grpc_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetM() *Matrix {
	if x != nil {
		return x.M
	}
	return nil
}

type Matrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M             []*Row                 `protobuf:"bytes,1,rep,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	mi := &file_grpc_grpc_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix) GetM() []*Row {
	if x != nil {
		return x.M
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []int32                `protobuf:"varint,1,rep,packed,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_grpc_grpc_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetRow() []int32 {
	if x != nil {
		return x.Row
	}
	return nil
}

var File_grpc_grpc_grpc_proto protoreflect.FileDescriptor

var file_grpc_grpc_grpc_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x55, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x70, 0x12, 0x1c, 0x0a, 0x02, 0x6d, 0x31, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x52, 0x02, 0x6d, 0x31, 0x12, 0x1c, 0x0a, 0x02, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52,
	0x02, 0x6d, 0x32, 0x22, 0x23, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x01,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x01, 0x6d, 0x22, 0x21, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72,
	0x69, 0x78, 0x12, 0x17, 0x0a, 0x01, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x01, 0x6d, 0x22, 0x17, 0x0a, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x6f, 0x77, 0x32, 0x30, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x4d, 0x75,
	0x6c, 0x12, 0x23, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_grpc_grpc_grpc_proto_rawDescOnce sync.Once
	file_grpc_grpc_grpc_proto_rawDescData []byte
)

func file_grpc_grpc_grpc_proto_rawDescGZIP() []byte {
	file_grpc_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_grpc_proto_rawDesc)))
	})
	return file_grpc_grpc_grpc_proto_rawDescData
}

var file_grpc_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_grpc_grpc_proto_goTypes = []any{
	(*Request)(nil), // 0: grpc.Request
	(*Reply)(nil),   // 1: grpc.Reply
	(*Matrix)(nil),  // 2: grpc.Matrix
	(*Row)(nil),     // 3: grpc.Row
}
var file_grpc_grpc_grpc_proto_depIdxs = []int32{
	2, // 0: grpc.Request.m1:type_name -> grpc.Matrix
	2, // 1: grpc.Request.m2:type_name -> grpc.Matrix
	2, // 2: grpc.Reply.m:type_name -> grpc.Matrix
	3, // 3: grpc.Matrix.m:type_name -> grpc.Row
	0, // 4: grpc.MatrixMul.Mul:input_type -> grpc.Request
	1, // 5: grpc.MatrixMul.Mul:output_type -> grpc.Reply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_grpc_grpc_proto_init() }
func file_grpc_grpc_grpc_proto_init() {
	if File_grpc_grpc_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_grpc_grpc_proto_msgTypes,
	}.Build()
	File_grpc_grpc_grpc_proto = out.File
	file_grpc_grpc_grpc_proto_goTypes = nil
	file_grpc_grpc_grpc_proto_depIdxs = nil
}
