// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: grpc/grpc/grpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatrixMul_Mul_FullMethodName = "/grpc.MatrixMul/Mul"
)

// MatrixMulClient is the client API for MatrixMul service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatrixMulClient interface {
	Mul(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type matrixMulClient struct {
	cc grpc.ClientConnInterface
}

func NewMatrixMulClient(cc grpc.ClientConnInterface) MatrixMulClient {
	return &matrixMulClient{cc}
}

func (c *matrixMulClient) Mul(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, MatrixMul_Mul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatrixMulServer is the server API for MatrixMul service.
// All implementations must embed UnimplementedMatrixMulServer
// for forward compatibility.
type MatrixMulServer interface {
	Mul(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedMatrixMulServer()
}

// UnimplementedMatrixMulServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatrixMulServer struct{}

func (UnimplementedMatrixMulServer) Mul(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mul not implemented")
}
func (UnimplementedMatrixMulServer) mustEmbedUnimplementedMatrixMulServer() {}
func (UnimplementedMatrixMulServer) testEmbeddedByValue()                   {}

// UnsafeMatrixMulServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatrixMulServer will
// result in compilation errors.
type UnsafeMatrixMulServer interface {
	mustEmbedUnimplementedMatrixMulServer()
}

func RegisterMatrixMulServer(s grpc.ServiceRegistrar, srv MatrixMulServer) {
	// If the following call pancis, it indicates UnimplementedMatrixMulServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatrixMul_ServiceDesc, srv)
}

func _MatrixMul_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatrixMulServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatrixMul_Mul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatrixMulServer).Mul(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MatrixMul_ServiceDesc is the grpc.ServiceDesc for MatrixMul service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatrixMul_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MatrixMul",
	HandlerType: (*MatrixMulServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mul",
			Handler:    _MatrixMul_Mul_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc/grpc.proto",
}
